#!/bin/bash

# get auth token from jenkins container (get_token)
 
if [ "$#" -ne 1 ]; then
    echo "Wrong number of parameters"
    exit 2
fi

if [ -f .api_token ];then
    echo "Found old auth token. Deleting"
    rm -f .api_token
fi

jenkins_container=$1

end=$((SECONDS+120))

while [ $SECONDS -lt $end ]; do
    TOKEN=$(docker exec ${jenkins_container} /bin/bash -c "cat /var/jenkins_home/.auth_token" 2>/dev/null)

    if [ -z ${TOKEN} ];then
        echo "---> Jenkins starting ..."
    else
        echo -e "\nAuth token created successfully : ${TOKEN}"
        echo -e "\nWritten to : .${jenkins_container}.auth_token"
        echo "${TOKEN}" > .${jenkins_container}.auth_token
        exit 0
    fi
    sleep 5
done

echo "[FAIL] ... Unable to get auth token from ${jenkins_container}"
exit 1
