#!/bin/bash

# This script is sourced from inside the dind container and these helper functions are used to :

# Start the Jenkinz Master 

jenkinz_image=$1

docker rm -f jenkins &> /dev/null

docker run -d --name jenkins -v /jenkinz/workspace:/jenkinz/workspace -p 8080:8080 -p 50000:50000 ${jenkinz_image} 

# There are 2 parts to this; wait for token to be created and wait for healthcheck to pass

echo "Waiting for auth token to be created"

token_end=$((SECONDS+120))

while [ $SECONDS -lt ${token_end} ]; do
    TOKEN=$(docker exec jenkins /bin/bash -c "cat /var/jenkins_home/.auth_token" 2>/dev/null)

    if [ -z ${TOKEN} ];then
        echo "---> Jenkins starting ..."
    else
        echo -e "\nAuth token created successfully : ${TOKEN}"
        echo -e "\nWritten to : .jenkins.auth_token"
        echo "${TOKEN}" > .jenkins.auth_token
        break 
    fi
    sleep 5
done

echo "Waiting for Jenkins Health Check to pass"
health_check_end=$((SECONDS+120))

while [ $SECONDS -lt ${health_check_end} ]; do

   curl -s http://0.0.0.0:8080/metrics/currentUser/healthcheck |grep "healthy" &>/dev/null

   if [ $? -eq 0 ];then
       echo "Health Check Passed. Jenkins is ready."
       exit 0
   else
       echo "Please wait while Jenkins is starting ..."
   fi
   sleep 5
done
