#!/bin/bash

# sync source code from user specified repository into build agent workspace 

if [ "$#" -ne 2 ]; then
    echo "Wrong number of parameters"
    exit 2
fi

src=$1
dest=$2

mkdir -p ${dest}
chmod 777 ${dest}
shopt -s dotglob;
cp -r ${src}/* ${dest}
chmod -R 777 ${dest}
#chown -R ${USER}:${USER} ${dest}

