name: CI

on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        source jenkinz.sh
        jenkinz -r demo
